// <auto-generated />
using System;
using BlazorWebAssembly.Server.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BlazorWebAssembly.Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220203175039_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("BlazorWebAssembly.Shared.Reserva", b =>
                {
                    b.Property<string>("Num_reserva")
                        .HasColumnType("nvarchar(450)");

                    b.Property<float>("Bill")
                        .HasColumnType("real");

                    b.Property<DateTime>("Fec_entrada")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Fec_salida")
                        .HasColumnType("datetime2");

                    b.Property<string>("Habitacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Num_adultos")
                        .HasColumnType("int");

                    b.Property<int>("Num_menores")
                        .HasColumnType("int");

                    b.Property<bool>("TermsAccepted")
                        .HasColumnType("bit");

                    b.Property<string>("Tip_pension")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("VIP")
                        .HasColumnType("bit");

                    b.HasKey("Num_reserva");

                    b.ToTable("Reservas");

                    b.HasData(
                        new
                        {
                            Num_reserva = "XHJ4321",
                            Bill = 100.25f,
                            Fec_entrada = new DateTime(2022, 2, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Fec_salida = new DateTime(2022, 2, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Habitacion = "103B",
                            Num_adultos = 2,
                            Num_menores = 0,
                            TermsAccepted = true,
                            Tip_pension = "Desayno y Cena",
                            VIP = false
                        },
                        new
                        {
                            Num_reserva = "JJJ333",
                            Bill = 100.25f,
                            Fec_entrada = new DateTime(2022, 2, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Fec_salida = new DateTime(2022, 2, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Habitacion = "103B",
                            Num_adultos = 2,
                            Num_menores = 0,
                            TermsAccepted = true,
                            Tip_pension = "Almuerzo y Cena",
                            VIP = false
                        },
                        new
                        {
                            Num_reserva = "ABC123",
                            Bill = 100.25f,
                            Fec_entrada = new DateTime(2022, 2, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Fec_salida = new DateTime(2022, 2, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Habitacion = "103B",
                            Num_adultos = 2,
                            Num_menores = 0,
                            TermsAccepted = true,
                            Tip_pension = "Cena",
                            VIP = false
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
