// <auto-generated />
using System;
using BlazorWebAssembly.Server.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BlazorWebAssembly.Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220215191505_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("BlazorWebAssembly.Shared.Documento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("DNI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("File64")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Documentos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DNI = "12549828R",
                            File64 = "iVBORw0KGgoAAAANSUhEUgAAAKAAAAChCAYAAABAk7SIAACAAElEQVR4XuydBXge55XvZZJsS8aYY2aZQWYmmdkyM8mWZCZZZMliZmaWLJmZYjtxEgccbNKkaZukTbe4bbe07ULPPb+jfNmun717e/cudW/meeaZ+eajmXn/7//8D7zvODl9vXy9fL3891uqa0udqmtKnaqqS75cS51qasucLl4653Tr9jWne/dvOr365JHT66+/pOuLTg8f3nK6fLnGqaQk2ykrK8kpIyPBKTMz0fazMpOe/fmvl6+XhiUvP80pOzfZKTsn2amgMNOptCzfqbKqqJGCr3NNbemGisqiFN2/VVlV8nF5RdGn5y/U/v2Dh3fl+o3L8s67b8ibbz6W9957/Y+PX773y4sXqz/Nzk76NCkp8t3k5OgLmZlJ63NyUoYrEJ/PzU1tVFaW51RZUejEtlD/Ky8v3SknW/9fV7ZfL//Dl+KSfKei4jxd8xVoCoTyQqfCoqz2WdlJa9LS428WFGV+rsf+WFVdLLXnKnQtk8KiHDlX",
                            Name = "Certificado de vacunacion"
                        },
                        new
                        {
                            Id = 2,
                            DNI = "12549828R",
                            File64 = "iVBORw0KGgoAAAANSUhEUgAAAKAAAAChCAYAAABAk7SIAACAAElEQVR4XuydBXge55XvZZJsS8aYY2aZQWYmmdkyM8mWZCZZZMliZmaWLJmZYjtxEgccbNKkaZukTbe4bbe07ULPPb+jfNmun717e/cudW/meeaZ+eajmXn/7//8D7zvODl9vXy9fL3891uqa0udqmtKnaqqS75cS51qasucLl4653Tr9jWne/dvOr365JHT66+/pOuLTg8f3nK6fLnGqaQk2ykrK8kpIyPBKTMz0fazMpOe/fmvl6+XhiUvP80pOzfZKTsn2amgMNOptCzfqbKqqJGCr3NNbemGisqiFN2/VVlV8nF5RdGn5y/U/v2Dh3fl+o3L8s67b8ibbz6W9957/Y+PX773y4sXqz/Nzk76NCkp8t3k5OgLmZlJ63NyUoYrEJ/PzU1tVFaW51RZUejEtlD/Ky8v3SknW/9fV7ZfL//Dl+KSfKei4jxd8xVoCoTyQqfCoqz2WdlJa9LS428WFGV+rsf+WFVdLLXnKnQtk8KiHDlX",
                            Name = "Declaracion jurada"
                        },
                        new
                        {
                            Id = 3,
                            DNI = "12549828R",
                            File64 = "iVBORw0KGgoAAAANSUhEUgAAAKAAAAChCAYAAABAk7SIAACAAElEQVR4XuydBXge55XvZZJsS8aYY2aZQWYmmdkyM8mWZCZZZMliZmaWLJmZYjtxEgccbNKkaZukTbe4bbe07ULPPb+jfNmun717e/cudW/meeaZ+eajmXn/7//8D7zvODl9vXy9fL3891uqa0udqmtKnaqqS75cS51qasucLl4653Tr9jWne/dvOr365JHT66+/pOuLTg8f3nK6fLnGqaQk2ykrK8kpIyPBKTMz0fazMpOe/fmvl6+XhiUvP80pOzfZKTsn2amgMNOptCzfqbKqqJGCr3NNbemGisqiFN2/VVlV8nF5RdGn5y/U/v2Dh3fl+o3L8s67b8ibbz6W9957/Y+PX773y4sXqz/Nzk76NCkp8t3k5OgLmZlJ63NyUoYrEJ/PzU1tVFaW51RZUejEtlD/Ky8v3SknW/9fV7ZfL//Dl+KSfKei4jxd8xVoCoTyQqfCoqz2WdlJa9LS428WFGV+rsf+WFVdLLXnKnQtk8KiHDlX",
                            Name = "Parte de viajero"
                        },
                        new
                        {
                            Id = 4,
                            DNI = "45381925D",
                            File64 = "iVBORw0KGgoAAAANSUhEUgAAAKAAAAChCAYAAABAk7SIAACAAElEQVR4XuydBXge55XvZZJsS8aYY2aZQWYmmdkyM8mWZCZZZMliZmaWLJmZYjtxEgccbNKkaZukTbe4bbe07ULPPb+jfNmun717e/cudW/meeaZ+eajmXn/7//8D7zvODl9vXy9fL3891uqa0udqmtKnaqqS75cS51qasucLl4653Tr9jWne/dvOr365JHT66+/pOuLTg8f3nK6fLnGqaQk2ykrK8kpIyPBKTMz0fazMpOe/fmvl6+XhiUvP80pOzfZKTsn2amgMNOptCzfqbKqqJGCr3NNbemGisqiFN2/VVlV8nF5RdGn5y/U/v2Dh3fl+o3L8s67b8ibbz6W9957/Y+PX773y4sXqz/Nzk76NCkp8t3k5OgLmZlJ63NyUoYrEJ/PzU1tVFaW51RZUejEtlD/Ky8v3SknW/9fV7ZfL//Dl+KSfKei4jxd8xVoCoTyQqfCoqz2WdlJa9LS428WFGV+rsf+WFVdLLXnKnQtk8KiHDlX",
                            Name = "Certificado de vacunacion"
                        },
                        new
                        {
                            Id = 5,
                            DNI = "45381925D",
                            File64 = "iVBORw0KGgoAAAANSUhEUgAAAKAAAAChCAYAAABAk7SIAACAAElEQVR4XuydBXge55XvZZJsS8aYY2aZQWYmmdkyM8mWZCZZZMliZmaWLJmZYjtxEgccbNKkaZukTbe4bbe07ULPPb+jfNmun717e/cudW/meeaZ+eajmXn/7//8D7zvODl9vXy9fL3891uqa0udqmtKnaqqS75cS51qasucLl4653Tr9jWne/dvOr365JHT66+/pOuLTg8f3nK6fLnGqaQk2ykrK8kpIyPBKTMz0fazMpOe/fmvl6+XhiUvP80pOzfZKTsn2amgMNOptCzfqbKqqJGCr3NNbemGisqiFN2/VVlV8nF5RdGn5y/U/v2Dh3fl+o3L8s67b8ibbz6W9957/Y+PX773y4sXqz/Nzk76NCkp8t3k5OgLmZlJ63NyUoYrEJ/PzU1tVFaW51RZUejEtlD/Ky8v3SknW/9fV7ZfL//Dl+KSfKei4jxd8xVoCoTyQqfCoqz2WdlJa9LS428WFGV+rsf+WFVdLLXnKnQtk8KiHDlX",
                            Name = "Declaracion jurada"
                        },
                        new
                        {
                            Id = 6,
                            DNI = "45381925D",
                            File64 = "iVBORw0KGgoAAAANSUhEUgAAAKAAAAChCAYAAABAk7SIAACAAElEQVR4XuydBXge55XvZZJsS8aYY2aZQWYmmdkyM8mWZCZZZMliZmaWLJmZYjtxEgccbNKkaZukTbe4bbe07ULPPb+jfNmun717e/cudW/meeaZ+eajmXn/7//8D7zvODl9vXy9fL3891uqa0udqmtKnaqqS75cS51qasucLl4653Tr9jWne/dvOr365JHT66+/pOuLTg8f3nK6fLnGqaQk2ykrK8kpIyPBKTMz0fazMpOe/fmvl6+XhiUvP80pOzfZKTsn2amgMNOptCzfqbKqqJGCr3NNbemGisqiFN2/VVlV8nF5RdGn5y/U/v2Dh3fl+o3L8s67b8ibbz6W9957/Y+PX773y4sXqz/Nzk76NCkp8t3k5OgLmZlJ63NyUoYrEJ/PzU1tVFaW51RZUejEtlD/Ky8v3SknW/9fV7ZfL//Dl+KSfKei4jxd8xVoCoTyQqfCoqz2WdlJa9LS428WFGV+rsf+WFVdLLXnKnQtk8KiHDlX",
                            Name = "Parte de viajero"
                        },
                        new
                        {
                            Id = 7,
                            DNI = "65232345C",
                            File64 = "iVBORw0KGgoAAAANSUhEUgAAAKAAAAChCAYAAABAk7SIAACAAElEQVR4XuydBXge55XvZZJsS8aYY2aZQWYmmdkyM8mWZCZZZMliZmaWLJmZYjtxEgccbNKkaZukTbe4bbe07ULPPb+jfNmun717e/cudW/meeaZ+eajmXn/7//8D7zvODl9vXy9fL3891uqa0udqmtKnaqqS75cS51qasucLl4653Tr9jWne/dvOr365JHT66+/pOuLTg8f3nK6fLnGqaQk2ykrK8kpIyPBKTMz0fazMpOe/fmvl6+XhiUvP80pOzfZKTsn2amgMNOptCzfqbKqqJGCr3NNbemGisqiFN2/VVlV8nF5RdGn5y/U/v2Dh3fl+o3L8s67b8ibbz6W9957/Y+PX773y4sXqz/Nzk76NCkp8t3k5OgLmZlJ63NyUoYrEJ/PzU1tVFaW51RZUejEtlD/Ky8v3SknW/9fV7ZfL//Dl+KSfKei4jxd8xVoCoTyQqfCoqz2WdlJa9LS428WFGV+rsf+WFVdLLXnKnQtk8KiHDlX",
                            Name = "Certificado de vacunacion"
                        },
                        new
                        {
                            Id = 8,
                            DNI = "65232345C",
                            File64 = "iVBORw0KGgoAAAANSUhEUgAAAKAAAAChCAYAAABAk7SIAACAAElEQVR4XuydBXge55XvZZJsS8aYY2aZQWYmmdkyM8mWZCZZZMliZmaWLJmZYjtxEgccbNKkaZukTbe4bbe07ULPPb+jfNmun717e/cudW/meeaZ+eajmXn/7//8D7zvODl9vXy9fL3891uqa0udqmtKnaqqS75cS51qasucLl4653Tr9jWne/dvOr365JHT66+/pOuLTg8f3nK6fLnGqaQk2ykrK8kpIyPBKTMz0fazMpOe/fmvl6+XhiUvP80pOzfZKTsn2amgMNOptCzfqbKqqJGCr3NNbemGisqiFN2/VVlV8nF5RdGn5y/U/v2Dh3fl+o3L8s67b8ibbz6W9957/Y+PX773y4sXqz/Nzk76NCkp8t3k5OgLmZlJ63NyUoYrEJ/PzU1tVFaW51RZUejEtlD/Ky8v3SknW/9fV7ZfL//Dl+KSfKei4jxd8xVoCoTyQqfCoqz2WdlJa9LS428WFGV+rsf+WFVdLLXnKnQtk8KiHDlX",
                            Name = "Declaracion jurada"
                        },
                        new
                        {
                            Id = 9,
                            DNI = "65232345C",
                            File64 = "iVBORw0KGgoAAAANSUhEUgAAAKAAAAChCAYAAABAk7SIAACAAElEQVR4XuydBXge55XvZZJsS8aYY2aZQWYmmdkyM8mWZCZZZMliZmaWLJmZYjtxEgccbNKkaZukTbe4bbe07ULPPb+jfNmun717e/cudW/meeaZ+eajmXn/7//8D7zvODl9vXy9fL3891uqa0udqmtKnaqqS75cS51qasucLl4653Tr9jWne/dvOr365JHT66+/pOuLTg8f3nK6fLnGqaQk2ykrK8kpIyPBKTMz0fazMpOe/fmvl6+XhiUvP80pOzfZKTsn2amgMNOptCzfqbKqqJGCr3NNbemGisqiFN2/VVlV8nF5RdGn5y/U/v2Dh3fl+o3L8s67b8ibbz6W9957/Y+PX773y4sXqz/Nzk76NCkp8t3k5OgLmZlJ63NyUoYrEJ/PzU1tVFaW51RZUejEtlD/Ky8v3SknW/9fV7ZfL//Dl+KSfKei4jxd8xVoCoTyQqfCoqz2WdlJa9LS428WFGV+rsf+WFVdLLXnKnQtk8KiHDlX",
                            Name = "Parte de viajero"
                        });
                });

            modelBuilder.Entity("BlazorWebAssembly.Shared.Huesped", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("DNI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Referencia")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Huespedes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Referencia = "XHJ4321"
                        },
                        new
                        {
                            Id = 2,
                            DNI = "12549828R",
                            Referencia = "JJJ333"
                        },
                        new
                        {
                            Id = 3,
                            DNI = "45381925D",
                            Referencia = "ABC123"
                        });
                });

            modelBuilder.Entity("BlazorWebAssembly.Shared.Reserva", b =>
                {
                    b.Property<string>("Num_reserva")
                        .HasColumnType("nvarchar(450)");

                    b.Property<float>("Bill")
                        .HasColumnType("real");

                    b.Property<DateTime>("Fec_entrada")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Fec_salida")
                        .HasColumnType("datetime2");

                    b.Property<string>("Habitacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Num_adultos")
                        .HasColumnType("int");

                    b.Property<int>("Num_menores")
                        .HasColumnType("int");

                    b.Property<bool>("TermsAccepted")
                        .HasColumnType("bit");

                    b.Property<string>("Tip_pension")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("VIP")
                        .HasColumnType("bit");

                    b.HasKey("Num_reserva");

                    b.ToTable("Reservas");

                    b.HasData(
                        new
                        {
                            Num_reserva = "XHJ4321",
                            Bill = 100.25f,
                            Fec_entrada = new DateTime(2022, 2, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Fec_salida = new DateTime(2022, 2, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Habitacion = "103B",
                            Num_adultos = 2,
                            Num_menores = 0,
                            TermsAccepted = true,
                            Tip_pension = "Desayno y Cena",
                            VIP = false
                        },
                        new
                        {
                            Num_reserva = "JJJ333",
                            Bill = 100.25f,
                            Fec_entrada = new DateTime(2022, 2, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Fec_salida = new DateTime(2022, 2, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Habitacion = "103B",
                            Num_adultos = 2,
                            Num_menores = 0,
                            TermsAccepted = true,
                            Tip_pension = "Almuerzo y Cena",
                            VIP = false
                        },
                        new
                        {
                            Num_reserva = "ABC123",
                            Bill = 100.25f,
                            Fec_entrada = new DateTime(2022, 2, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Fec_salida = new DateTime(2022, 2, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Habitacion = "103B",
                            Num_adultos = 2,
                            Num_menores = 0,
                            TermsAccepted = true,
                            Tip_pension = "Cena",
                            VIP = false
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
