// <auto-generated />
using BlazorWebAssembly.Server.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BlazorWebAssembly.Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("BlazorWebAssembly.Shared.Reserva", b =>
                {
                    b.Property<string>("Num_reserva")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Num_reserva");

                    b.ToTable("Reservas");

                    b.HasData(
                        new
                        {
                            Num_reserva = "XHJ4321"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
